apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agapesistemas-PROJETO-hpa
  namespace: agapesistemas-ns-AMBIENTE
spec:
  maxReplicas: 3
  metrics:    
    - resource:
        name: memory
        target:
          averageValue: 6000Mi
          type: AverageValue
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: PROJETO-dp-AMBIENTE