apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agapesistemas-PROJETOAMBIENTE-tls
  namespace: agapesistemas-ns-AMBIENTE
spec:
  dnsNames:
    - PROJETOAMBIENTE.agapesistemas.com.br
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: agapesistemas-PROJETOAMBIENTE-tls