apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: 'true'
    #traefik.ingress.kubernetes.io/service.sticky.cookie.name: JSESSIONID
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: 'true'
  name: agapesistemas-PROJETO-svc
  namespace: agapesistemas-ns-AMBIENTE
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: PROJETO
  type: ClusterIP
